1. df['age'] filtered outliers >80 years old;
2. df['diet'] - simplified to 6 categories ('Anything','Vegetarian','Other','Vegan','Halal','Kosher')
3. df['body_type'], df['job']  NaN values filled with 'rather not say'
df['drinks'], df['drugs'] NaN values filled with 'unknown'
4. df['education'] was transformed into 2 columns
first one show the level that person have is/was working on and second df['education_status'] show if person is actually studying or was dropped of or graduated;
5.  df['ethnicity'] Simplified, cause we had too many options.
So a) values  'black, other', 'asian, other', 'white,other' and others were changed as black,asian and white. 
b) values with a lot of different options were grouped as mixed
6. df['height'] -  metrics were changed to cm and outliers <135 cm and >210;
7. df['last_online'] no changes
8. df['pets']  was transformed as binary features of preferences (for ML)
df['likes_dogs'] = df['pets'].apply(lambda x: 1 if 'likes dogs' in x else 0)
df['likes_cats'] = df['pets'].apply(lambda x: 1 if 'likes cats' in x else 0)
df['has_dogs'] = df['pets'].apply(lambda x: 1 if 'has dogs' in x else 0)
df['has_cats'] = df['pets'].apply(lambda x: 1 if 'has cats' in x else 0)
df['dislikes_dogs'] = df['pets'].apply(lambda x: 1 if 'dislikes dogs' in x else 0)
df['dislikes_cats'] = df['pets'].apply(lambda x: 1 if 'dislikes cats' in x else 0)
9. df['offspring'] was changed into 2 columns  df['Kids'] and df['Want kids']
10. df['speaks'] was transofred into boolean-columns that show most used languages  [English_Proficiency,Spanish_Proficiency, French_Proficiency, German_Proficiency, Chinese_Proficiency,Italian_Proficiency,Russian_Proficiency, Hindi_Proficiency, Portuguese_Proficiency, Hebrew_Proficiency]
11. df['income'] transformed to df['income_category'] where 0 means - dont want to share data (biggest group) and groips from 1 to 12 are categories from lowest to biggest.
12. df[religion] was simplified and created also  df['religiosity_level'] to show a personal attitude to religion ('not_serious'laughing', 'somewhat_serious', 'very_serious')
13. df['sign'] was transformed into df['astrology'] that same as df['religiosity_level'] show  the attitude to astrology ('not_serious','laughing',fun to think about" ,'serious')

In [1]:
import pandas as pd
import numpy as np

In [2]:
original = pd.read_csv('okcupid_profiles.csv')
df = pd.read_csv('okcupid_profiles_cleaned.csv')

In [3]:
df

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,income,job,last_online,location,offspring,pets,religion,sign,smokes,speaks
0,22,single,m,straight,a little extra,strictly anything,socially,never,working on college/university,"asian, white",...,-1,transportation,2012-06-28-20-30,"south san francisco, california","doesn't have kids, but might want them",likes dogs and likes cats,agnosticism and very serious about it,gemini,sometimes,english
1,35,single,m,straight,average,mostly other,often,sometimes,working on space camp,white,...,80000,hospitality / travel,2012-06-29-21-41,"oakland, california","doesn't have kids, but might want them",likes dogs and likes cats,agnosticism but not too serious about it,cancer,no,"english (fluently), spanish (poorly), french (..."
2,38,available,m,straight,thin,anything,socially,NaN,graduated from masters program,NaN,...,-1,NaN,2012-06-27-09-10,"san francisco, california",NaN,has cats,NaN,pisces but it doesn&rsquo;t matter,no,"english, french, c++"
3,23,single,m,straight,thin,vegetarian,socially,NaN,working on college/university,white,...,20000,student,2012-06-28-14-22,"berkeley, california",doesn't want kids,likes cats,NaN,pisces,no,"english, german (poorly)"
4,29,single,m,straight,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",...,-1,artistic / musical / writer,2012-06-27-21-26,"san francisco, california",NaN,likes dogs and likes cats,NaN,aquarius,no,english
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,single,f,straight,NaN,NaN,socially,never,graduated from college/university,NaN,...,-1,sales / marketing / biz dev,2012-06-12-21-47,"oakland, california",has kids,has dogs,catholicism but not too serious about it,cancer and it&rsquo;s fun to think about,no,english
59942,24,single,m,straight,fit,mostly anything,often,sometimes,working on college/university,"white, other",...,-1,entertainment / media,2012-06-29-11-01,"san francisco, california",doesn't have kids,likes dogs and likes cats,agnosticism,leo but it doesn&rsquo;t matter,no,english (fluently)
59943,42,single,m,straight,average,mostly anything,not at all,never,graduated from masters program,asian,...,100000,construction / craftsmanship,2012-06-27-23-37,"south san francisco, california",doesn't have kids,NaN,christianity but not too serious about it,sagittarius but it doesn&rsquo;t matter,no,english (fluently)
59944,27,single,m,straight,athletic,mostly anything,socially,often,working on college/university,"asian, black",...,-1,medicine / health,2012-06-23-13-01,"san francisco, california","doesn't have kids, but wants them",likes dogs and likes cats,agnosticism but not too serious about it,leo and it&rsquo;s fun to think about,trying to quit,"english (fluently), spanish (poorly), chinese ..."
59945,39,single,m,gay,average,NaN,socially,NaN,graduated from masters program,white,...,-1,medicine / health,2012-06-29-00-42,"san francisco, california",NaN,likes dogs and likes cats,catholicism and laughing about it,gemini and it&rsquo;s fun to think about,sometimes,english

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  int64
 1   status       59946 non-null  object
 2   sex          59946 non-null  object
 3   orientation  59946 non-null  object
 4   body_type    54650 non-null  object
 5   diet         35551 non-null  object
 6   drinks       56961 non-null  object
 7   drugs        45866 non-null  object
 8   education    53318 non-null  object
 9   ethnicity    54266 non-null  object
 10  height       59943 non-null  float64
 11  income       59946 non-null  int64
 12  job          51748 non-null  object
 13  last_online  59946 non-null  object
 14  location     59946 non-null  object
 15  offspring    24385 non-null  object
 16  pets         40025 non-null  object
 17  religion     39720 non-null  object
 18  sign         48890 non-null  object
 19  smokes       54434 non-null  object
 20  speaks       59896 non-null  object
dtypes: float64(1), int64(2), object(18)
memory usage: 9.6+ MB

In [6]:
df['height_cm'] = df['height'] * 2.54
df.drop(df[(df['height_cm'] < 135) | (df['height_cm'] > 210)].index, inplace=True)

In [7]:
df.drop(df[df['age'] > 80].index, inplace=True)

In [8]:
df['body_type'].fillna('rather not say', inplace=True)
df['drinks'].fillna('unknown', inplace=True)
df['drugs'].fillna('unknown', inplace=True)

In [9]:
df['diet'] = df['diet'].apply(lambda x: 'Other' if pd.isna(x) else
                              'Anything' if x in ['mostly anything', 'anything', 'strictly anything'] else
                              'Vegetarian' if x in ['mostly vegetarian', 'strictly vegetarian', 'vegetarian'] else
                              'Other' if x in ['strictly other', 'other', 'mostly other'] else
                              'Vegan' if x in ['vegan', 'strictly vegan', 'mostly vegan'] else
                              'Halal' if x in ['strictly halal', 'halal', 'mostly halal'] else
                              'Kosher' if x in ['strictly kosher', 'kosher', 'mostly kosher'] else x)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59853 entries, 0 to 59945
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59853 non-null  int64
 1   status       59853 non-null  object
 2   sex          59853 non-null  object
 3   orientation  59853 non-null  object
 4   body_type    59853 non-null  object
 5   diet         59853 non-null  object
 6   drinks       59853 non-null  object
 7   drugs        59853 non-null  object
 8   education    53245 non-null  object
 9   ethnicity    54195 non-null  object
 10  height       59850 non-null  float64
 11  income       59853 non-null  int64
 12  job          51677 non-null  object
 13  last_online  59853 non-null  object
 14  location     59853 non-null  object
 15  offspring    24354 non-null  object
 16  pets         39960 non-null  object
 17  religion     39658 non-null  object
 18  sign         48818 non-null  object
 19  smokes       54359 non-null  object
 20  speaks       59803 non-null  object
 21  height_cm    59850 non-null  float64
dtypes: float64(2), int64(2), object(18)
memory usage: 10.5+ MB

In [11]:
df['sign'].unique()

array(['gemini', 'cancer', 'pisces but it doesn&rsquo;t matter', 'pisces',
       'aquarius', 'taurus', 'virgo', 'sagittarius',
       'gemini but it doesn&rsquo;t matter',
       'cancer but it doesn&rsquo;t matter',
       'leo but it doesn&rsquo;t matter', nan,
       'aquarius but it doesn&rsquo;t matter',
       'aries and it&rsquo;s fun to think about',
       'libra but it doesn&rsquo;t matter',
       'pisces and it&rsquo;s fun to think about', 'libra',
       'taurus but it doesn&rsquo;t matter',
       'sagittarius but it doesn&rsquo;t matter',
       'scorpio and it matters a lot',
       'gemini and it&rsquo;s fun to think about',
       'leo and it&rsquo;s fun to think about',
       'cancer and it&rsquo;s fun to think about',
       'libra and it&rsquo;s fun to think about',
       'aquarius and it&rsquo;s fun to think about',
       'virgo but it doesn&rsquo;t matter',
       'scorpio and it&rsquo;s fun to think about',
       'capricorn but it doesn&rsquo;t matter', 'scorpio',
       'capricorn and it&rsquo;s fun to think about', 'leo',
       'aries but it doesn&rsquo;t matter', 'aries',
       'scorpio but it doesn&rsquo;t matter',
       'sagittarius and it&rsquo;s fun to think about',
       'libra and it matters a lot',
       'taurus and it&rsquo;s fun to think about',
       'leo and it matters a lot',
       'virgo and it&rsquo;s fun to think about',
       'cancer and it matters a lot', 'capricorn',
       'pisces and it matters a lot', 'aries and it matters a lot',
       'capricorn and it matters a lot', 'aquarius and it matters a lot',
       'sagittarius and it matters a lot', 'gemini and it matters a lot',
       'taurus and it matters a lot', 'virgo and it matters a lot'],
      dtype=object)

In [12]:
df['astrology'] = df['sign'].apply(lambda x: 'not_serious' if pd.notna(x) and "doesn" in x else
                                               'laughing' if pd.notna(x) and "fun to think about" in x else
                                               'serious' if pd.notna(x) and 'it matters a lot' in x else 'unknown')

In [13]:
df['religion_new'] = df['religion'].apply(lambda x: x.split()[0] if isinstance(x, str) and x.split()[0] != 'other' else 'other_religion' if isinstance(x, str) else np.nan)

In [14]:
df['religiosity_level'] = df['religion'].apply(lambda x: 'not_serious' if pd.notna(x) and 'not too serious' in x else
                                               'laughing' if pd.notna(x) and 'laughing about it' in x else
                                               'somewhat_serious' if pd.notna(x) and 'somewhat serious about it' in x else
                                               'very_serious' if pd.notna(x) and 'very serious about it' in x else 'unknown')

In [15]:
df['education_status'] = df['education'].apply(lambda x: 'studying' if pd.notna(x) and 'working on' in str(x) else
                                                'dropped out' if pd.notna(x) and 'dropped out' in str(x) else
                                                'Graduated' if pd.notna(x) and 'graduated' in str(x) else 'unknown')
df['education'] = df['education'].str.split('from|of|on').str[-1].str.strip()

In [16]:
df['education'].value_counts()

education
college/university    31439
masters program       10913
two-year college       3013
ph.d program           2402
high school            1703
space camp             1670
law school             1424
med school              681
Name: count, dtype: int64

In [17]:
df['religiosity_level'].value_counts()

religiosity_level
unknown             31961
not_serious         12198
laughing             8976
somewhat_serious     4511
very_serious         2207
Name: count, dtype: int64

In [18]:
df['religion_new'].value_counts()

religion_new
agnosticism       8800
other_religion    7725
atheism           6978
christianity      5779
catholicism       4752
judaism           3094
buddhism          1945
hinduism           449
islam              136
Name: count, dtype: int64

In [19]:
df['likes_dogs'] = df['pets'].apply(lambda x: 1 if pd.notna(x) and 'likes dogs' in x else 0)
df['likes_cats'] = df['pets'].apply(lambda x: 1  if pd.notna(x) and 'likes cats' in x else 0)
df['has_dogs'] = df['pets'].apply(lambda x: 1 if pd.notna(x) and 'has dogs' in x else 0)
df['has_cats'] = df['pets'].apply(lambda x: 1 if pd.notna(x) and 'has cats' in x else 0)
df['dislikes_dogs'] = df['pets'].apply(lambda x: 1 if pd.notna(x) and 'dislikes dogs' in x else 0)
df['dislikes_cats'] = df['pets'].apply(lambda x: 1 if pd.notna(x) and 'dislikes cats' in x else 0)

In [20]:
df['pets'].value_counts()

pets
likes dogs and likes cats          14793
likes dogs                          7218
likes dogs and has cats             4308
has dogs                            4127
has dogs and likes cats             2327
likes dogs and dislikes cats        2027
has dogs and has cats               1469
has cats                            1402
likes cats                          1062
has dogs and dislikes cats           549
dislikes dogs and likes cats         237
dislikes dogs and dislikes cats      194
dislikes cats                        122
dislikes dogs and has cats            81
dislikes dogs                         44
Name: count, dtype: int64

In [21]:
df.columns

Index(['age', 'status', 'sex', 'orientation', 'body_type', 'diet', 'drinks',
       'drugs', 'education', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'pets', 'religion', 'sign',
       'smokes', 'speaks', 'height_cm', 'astrology', 'religion_new',
       'religiosity_level', 'education_status', 'likes_dogs', 'likes_cats',
       'has_dogs', 'has_cats', 'dislikes_dogs', 'dislikes_cats'],
      dtype='object')

In [22]:
df['offspring'].value_counts()

offspring
doesn't have kids                          7552
doesn't have kids, but might want them     3873
doesn't have kids, but wants them          3560
doesn't want kids                          2919
has kids                                   1880
has a kid                                  1879
doesn't have kids, and doesn't want any    1132
has kids, but doesn't want more             441
has a kid, but doesn't want more            274
has a kid, and might want more              231
wants kids                                  225
might want kids                             181
has kids, and might want more               115
has a kid, and wants more                    71
has kids, and wants more                     21
Name: count, dtype: int64

In [23]:
nan_mask = df['offspring'].isna()

df['Kids'] = df['offspring'].apply(lambda x: 0 if pd.isna(x) else 
                                   0 if 'doesn\'t have kids' in x or 'has no kids' in x or 'doesn\'t want kids' in x else 
                                   1 if 'has a kid' in x or 'have one' in x else 
                                   2 if 'has kids' in x and 'doesn\'t want more' not in x else None)

df['Want kids'] = df['offspring'].apply(lambda x: None if pd.isna(x) else 
                                        'Yes' if 'wants them' in x or 'might want more' in x or 'might want kids' in x else 
                                        'No' if 'doesn\'t want any' in x or 'doesn\'t want more' in x or 'doesn\'t want kids' in x else 
                                        'Maybe' if 'but wants them' in x or 'but might want them' in x else None)

In [24]:
df['Kids'].value_counts()

Kids
0.0    54535
1.0     2455
2.0     2016
Name: count, dtype: int64

In [25]:
df['Want kids'].value_counts()

Want kids
No       4766
Yes      4087
Maybe    3873
Name: count, dtype: int64

In [26]:
df['speaks'].value_counts()

speaks
english                                                                  21788
english (fluently)                                                        6620
english (fluently), spanish (poorly)                                      2055
english (fluently), spanish (okay)                                        1916
english (fluently), spanish (fluently)                                    1288
                                                                         ...
english (fluently), japanese (okay), thai (okay), chinese (poorly)           1
english (fluently), french (okay), italian (okay), hebrew (okay)             1
english (fluently), farsi (poorly), spanish (poorly), french (poorly)        1
english (okay), tagalog (okay), japanese (poorly), french (poorly)           1
english (fluently), french, farsi                                            1
Name: count, Length: 7629, dtype: int64

In [27]:
speaks_data = df['speaks'].dropna()  # Drop NaN values

all_languages = ', '.join(speaks_data) # Concatenate all strings in the 'speaks' column
# Split the concatenated string into a list of languages
languages_list = [language.strip() for language in all_languages.split(',')]

# Create a DataFrame to count occurrences of each language
languages_df = pd.DataFrame(languages_list, columns=['Language'])
top_20_languages = languages_df['Language'].value_counts().head(50).reset_index()

top_20_languages.columns = ['Language', 'Count']
top_20_languages

                  Language  Count
0                  english  30246
1       english (fluently)  28243
2         spanish (poorly)   6268
3           spanish (okay)   5531
4          french (poorly)   3618
5       spanish (fluently)   3051
6            french (okay)   2539
7          german (poorly)   1499
8                  spanish   1440
9        japanese (poorly)   1241
10      chinese (fluently)   1150
11          english (okay)   1117
12          chinese (okay)   1087
13       french (fluently)   1083
14        italian (poorly)   1022
15        chinese (poorly)    928
16           german (okay)    840
17          italian (okay)    697
18          c++ (fluently)    662
19        english (poorly)    647
20                  french    603
21         japanese (okay)    569
22              c++ (okay)    531
23      russian (fluently)    520
24       german (fluently)    504
25                 chinese    493
26        other (fluently)    427
27            c++ (poorly)    407
28     portuguese (poorly)    400
29  sign language (poorly)    399
30        russian (poorly)    357
31         hebrew (poorly)    350
32        hindi (fluently)    314
33    sign language (okay)    296
34      italian (fluently)    289
35       portuguese (okay)    287
36          latin (poorly)    280
37   portuguese (fluently)    276
38         arabic (poorly)    260
39        tagalog (poorly)    240
40      tagalog (fluently)    237
41                  german    236
42     japanese (fluently)    226
43         korean (poorly)    224
44          russian (okay)    207
45                 russian    199
46          tagalog (okay)    192
47            other (okay)    190
48       hebrew (fluently)    181
49           hebrew (okay)    178

In [28]:
languages_list = ['english', 'spanish', 'french', 'german', 'chinese', 'italian', 'russian', 'hindi', 'portuguese', 'hebrew']

# Iterate over languages and create a column
for language in languages_list:
    column_name = f'{language.capitalize()}_Proficiency'
    df[column_name] = df['speaks'].apply(lambda x: 'Yes' if language in str(x).lower() else 'No')
display(df)

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,English_Proficiency,Spanish_Proficiency,French_Proficiency,German_Proficiency,Chinese_Proficiency,Italian_Proficiency,Russian_Proficiency,Hindi_Proficiency,Portuguese_Proficiency,Hebrew_Proficiency
0,22,single,m,straight,a little extra,Anything,socially,never,college/university,"asian, white",...,Yes,No,No,No,No,No,No,No,No,No
1,35,single,m,straight,average,Other,often,sometimes,space camp,white,...,Yes,Yes,Yes,No,No,No,No,No,No,No
2,38,available,m,straight,thin,Anything,socially,unknown,masters program,NaN,...,Yes,No,Yes,No,No,No,No,No,No,No
3,23,single,m,straight,thin,Vegetarian,socially,unknown,college/university,white,...,Yes,No,No,Yes,No,No,No,No,No,No
4,29,single,m,straight,athletic,Other,socially,never,college/university,"asian, black, other",...,Yes,No,No,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,single,f,straight,rather not say,Other,socially,never,college/university,NaN,...,Yes,No,No,No,No,No,No,No,No,No
59942,24,single,m,straight,fit,Anything,often,sometimes,college/university,"white, other",...,Yes,No,No,No,No,No,No,No,No,No
59943,42,single,m,straight,average,Anything,not at all,never,masters program,asian,...,Yes,No,No,No,No,No,No,No,No,No
59944,27,single,m,straight,athletic,Anything,socially,often,college/university,"asian, black",...,Yes,Yes,No,No,Yes,No,No,No,No,No
59945,39,single,m,gay,average,Other,socially,unknown,masters program,white,...,Yes,No,No,No,No,No,No,No,No,No

In [29]:
df['job'].fillna('rather not say', inplace=True)
df['job'].value_counts()

job
rather not say                       8609
other                                7579
student                              4871
science / tech / engineering         4843
computer / hardware / software       4704
artistic / musical / writer          4434
sales / marketing / biz dev          4389
medicine / health                    3678
education / academia                 3509
executive / management               2371
banking / financial / real estate    2264
entertainment / media                2245
law / legal services                 1379
hospitality / travel                 1362
construction / craftsmanship         1019
clerical / administrative             805
political / government                706
transportation                        365
unemployed                            271
retired                               248
military                              202
Name: count, dtype: int64

In [30]:
ethnicity_counts = df['ethnicity'].value_counts()
display(ethnicity_counts.head(50))

ethnicity
white                                                                                                      32808
asian                                                                                                       6130
hispanic / latin                                                                                            2815
black                                                                                                       2004
other                                                                                                       1696
hispanic / latin, white                                                                                     1298
indian                                                                                                      1077
asian, white                                                                                                 809
white, other                                                                                                 641
pacific islander                                                                                             431
asian, pacific islander                                                                                      395
native american, white                                                                                       337
middle eastern                                                                                               328
middle eastern, white                                                                                        300
black, white                                                                                                 297
pacific islander, white                                                                                      156
hispanic / latin, other                                                                                      137
black, other                                                                                                 133
black, hispanic / latin                                                                                      119
hispanic / latin, white, other                                                                               117
black, native american, white                                                                                109
black, native american                                                                                       100
asian, other                                                                                                  95
asian, hispanic / latin                                                                                       88
native american, hispanic / latin, white                                                                      87
native american, hispanic / latin                                                                             73
asian, white, other                                                                                           69
native american                                                                                               65
asian, middle eastern, black, native american, indian, pacific islander, hispanic / latin, white, other       61
asian, black                                                                                                  59
pacific islander, hispanic / latin                                                                            56
asian, pacific islander, white                                                                                55
native american, white, other                                                                                 54
asian, indian                                                                                                 52
black, white, other                                                                                           49
indian, white                                                                                                 46
asian, hispanic / latin, white                                                                                41
middle eastern, white, other                                                                                  40
middle eastern, hispanic / latin                                                                              39
asian, pacific islander, other                                                                                38
black, hispanic / latin, white                                                                                36
native american, hispanic / latin, white, other                                                               33
indian, other                                                                                                 30
pacific islander, hispanic / latin, white                                                                     30
black, native american, white, other                                                                          29
black, native american, other                                                                                 27
black, native american, hispanic / latin, white                                                               26
middle eastern, other                                                                                         23
black, native american, hispanic / latin                                                                      19
pacific islander, white, other                                                                                18
Name: count, dtype: int64

In [31]:
df['ethnicity'] = df['ethnicity'].replace('white, other', 'white') # Replace 'white, other' with 'white'
df['ethnicity'] = df['ethnicity'].replace('black, other', 'black') 
df['ethnicity'] = df['ethnicity'].replace('asian, other', 'asian')

In [32]:
df['ethnicity'].fillna('unknown', inplace=True)
df['ethnicity'] = df['ethnicity'].apply(lambda x: 'mixed' if x.count(',') >= 2 else x)

In [33]:
df['ethnicity'] = df['ethnicity'].str.replace(', other', '')

In [34]:
df['ethnicity'] = df['ethnicity'].apply(lambda x: 'mixed' if x.count(',') >= 1 else x) #important to do it twice and in this order

In [35]:
df['ethnicity'].value_counts()

ethnicity
white               33449
asian                6225
mixed                5752
unknown              5658
hispanic / latin     2952
black                2137
other                1696
indian               1107
pacific islander      445
middle eastern        351
native american        81
Name: count, dtype: int64

In [36]:
df['smokes'].fillna('unknown', inplace=True)
df['smokes'].value_counts()

smokes
no                43852
unknown            5494
sometimes          3779
when drinking      3031
yes                2220
trying to quit     1477
Name: count, dtype: int64

In [37]:
df['income'] = df['income'].replace(-1, 0)
df['income'] = pd.Categorical(df['income'], ordered=True)
df['income_category'] = df['income'].cat.codes
df['income_category'].value_counts()

income_category
0     48381
1      2942
8      1620
7      1110
2      1046
3      1005
4       974
5       736
6       706
9       628
12      509
10      149
11       47
Name: count, dtype: int64

In [38]:
df = df.drop(['height', 'religion', 'sign', 'offspring', 'pets'], axis=1)

In [39]:
df['religion_new'].fillna('unknown', inplace=True)
df.rename(columns={'religion_new': 'religion'}, inplace=True)

In [40]:
df.dropna(subset=['height_cm'], inplace=True)

In [43]:
df = df.drop(['income', 'speaks', 'location'], axis=1)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59850 entries, 0 to 59945
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     59850 non-null  int64
 1   status                  59850 non-null  object
 2   sex                     59850 non-null  object
 3   orientation             59850 non-null  object
 4   body_type               59850 non-null  object
 5   diet                    59850 non-null  object
 6   drinks                  59850 non-null  object
 7   drugs                   59850 non-null  object
 8   education               53245 non-null  object
 9   ethnicity               59850 non-null  object
 10  job                     59850 non-null  object
 11  last_online             59850 non-null  object
 12  location                59850 non-null  object
 13  smokes                  59850 non-null  object
 14  height_cm               59850 non-null  float64
 15  astrology               59850 non-null  object
 16  religion                59850 non-null  object
 17  religiosity_level       59850 non-null  object
 18  education_status        59850 non-null  object
 19  likes_dogs              59850 non-null  int64
 20  likes_cats              59850 non-null  int64
 21  has_dogs                59850 non-null  int64
 22  has_cats                59850 non-null  int64
 23  dislikes_dogs           59850 non-null  int64
 24  dislikes_cats           59850 non-null  int64
 25  Kids                    59003 non-null  float64
 26  Want kids               12726 non-null  object
 27  English_Proficiency     59850 non-null  object
 28  Spanish_Proficiency     59850 non-null  object
 29  French_Proficiency      59850 non-null  object
 30  German_Proficiency      59850 non-null  object
 31  Chinese_Proficiency     59850 non-null  object
 32  Italian_Proficiency     59850 non-null  object
 33  Russian_Proficiency     59850 non-null  object
 34  Hindi_Proficiency       59850 non-null  object
 35  Portuguese_Proficiency  59850 non-null  object
 36  Hebrew_Proficiency      59850 non-null  object
 37  income_category         59850 non-null  int8
dtypes: float64(2), int64(7), int8(1), object(28)
memory usage: 17.4+ MB

In [42]:
file_path = 'D:\ReDi Data Analytics\okcupid\okcupid_new.csv'
df.to_csv(file_path, index=False)

print(f'DataFrame has been saved to {file_path}')

DataFrame has been saved to D:\ReDi Data Analytics\okcupid\okcupid_new.csv

In [4]:
!pip install skimpy
from skimpy import skim
skim(df)

Requirement already satisfied: skimpy in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (0.0.11)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (2.16.1)
Requirement already satisfied: click<9.0.0,>=8.1.6 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (8.1.7)
Requirement already satisfied: ipykernel<7.0.0,>=6.7.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (6.25.2)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (1.0.0)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (1.25.2)
Requirement already satisfied: pandas<3.0.0,>=2.0.3 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (2.0.3)
Requirement already satisfied: polars<0.20.0,>=0.19.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (0.19.19)
Requirement already satisfied: pyarrow<14.0.0,>=13.0.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (13.0.0)
Requirement already satisfied: rich<14.0,>=10.9 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (13.7.0)
Requirement already satisfied: typeguard==4.1.4 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from skimpy) (4.1.4)
Requirement already satisfied: typing-extensions>=4.7.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from typeguard==4.1.4->skimpy) (4.7.1)
Requirement already satisfied: colorama in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from click<9.0.0,>=8.1.6->skimpy) (0.4.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (8.15.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (8.3.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.3.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.5.6)
Requirement already satisfied: packaging in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (23.1)
Requirement already satisfied: psutil in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.9.0)
Requirement already satisfied: pyzmq>=20 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.9.0)
Requirement already satisfied: notebook in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (7.0.6)
Requirement already satisfied: qtconsole in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (5.5.1)
Requirement already satisfied: jupyter-console in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (7.12.0)
Requirement already satisfied: ipywidgets in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (8.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2023.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from rich<14.0,>=10.9->skimpy) (3.0.0)
Requirement already satisfied: backcall in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.0)
Requirement already satisfied: decorator in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.19.0)
Requirement already satisfied: pickleshare in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.39)
Requirement already satisfied: stack-data in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.6.2)
Requirement already satisfied: exceptiongroup in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (1.1.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel<7.0.0,>=6.7.0->skimpy) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel<7.0.0,>=6.7.0->skimpy) (305.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0,>=10.9->skimpy) (0.1.2)
Requirement already satisfied: six>=1.5 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.3->skimpy) (1.16.0)
Requirement already satisfied: widgetsnbextension~=4.0.9 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (4.0.9)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (3.0.9)
Requirement already satisfied: beautifulsoup4 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (4.12.2)
Requirement already satisfied: bleach!=5.0.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (3.1.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.1.3)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.9.0)
Requirement already satisfied: nbformat>=5.7 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (5.9.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.2.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.12.1)
Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.25.2)
Requirement already satisfied: jupyterlab<5,>=4.0.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (4.0.9)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.2.3)
Requirement already satisfied: qtpy>=2.4.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from qtconsole->jupyter<2.0.0,>=1.0.0->skimpy) (2.4.1)
Requirement already satisfied: webencodings in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.8.3)
Requirement already satisfied: anyio>=3.1.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (4.1.0)
Requirement already satisfied: argon2-cffi in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.9.0)
Requirement already satisfied: jupyter-server-terminals in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.4.4)
Requirement already satisfied: overrides in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (7.4.0)
Requirement already satisfied: prometheus-client in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.19.0)
Requirement already satisfied: pywinpty in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.0.12)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.18.0)
Requirement already satisfied: websocket-client in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.7.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.0.4)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.2.1)
Requirement already satisfied: tomli in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.0.1)
Requirement already satisfied: babel>=2.10 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.13.1)
Requirement already satisfied: json5>=0.9.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.9.14)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (4.20.0)
Requirement already satisfied: requests>=2.31 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.31.0)
Requirement already satisfied: fastjsonschema in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.19.0)
Requirement already satisfied: wcwidth in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.6)
Requirement already satisfied: soupsieve>1.2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from beautifulsoup4->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (2.4.0)
Requirement already satisfied: pure-eval in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.2)
Requirement already satisfied: idna>=2.8 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (3.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.3.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2023.11.2)
Requirement already satisfied: referencing>=0.28.4 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.32.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.13.2)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2023.11.17)
Requirement already satisfied: argon2-cffi-bindings in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (21.2.0)
Requirement already satisfied: fqdn in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.5.1)
Requirement already satisfied: isoduration in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.4)
Requirement already satisfied: uri-template in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.3.0)
Requirement already satisfied: webcolors>=1.11 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.13)
Requirement already satisfied: cffi>=1.0.1 in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.16.0)
Requirement already satisfied: pycparser in c:\users\iurii novachynskyi\anaconda3\envs\cab\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.21)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 59946  │ │ string      │ 18    │                                                          │
│ │ Number of columns │ 21     │ │ int32       │ 2     │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column_name      ┃ NA   ┃ NA %   ┃ mean     ┃ sd       ┃ p0   ┃ p25   ┃ p50   ┃ p75  ┃ p100      ┃ hist    ┃  │
│ ┡━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━┩  │
│ │ age              │    0 │      0 │       32 │      9.5 │   18 │    26 │    30 │   37 │       110 │   ▇▃▁   │  │
│ │ height           │    3 │   0.01 │       68 │        4 │    1 │    66 │    68 │   71 │        95 │     ▁▇  │  │
│ │ income           │    0 │      0 │    20000 │    97000 │   -1 │    -1 │    -1 │   -1 │   1000000 │    ▇    │  │
│ └──────────────────┴──────┴────────┴──────────┴──────────┴──────┴───────┴───────┴──────┴───────────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name             ┃ NA           ┃ NA %        ┃ words per row              ┃ total words            ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ status                  │            0 │           0 │                          1 │                  62010 │  │
│ │ sex                     │            0 │           0 │                          1 │                  59946 │  │
│ │ orientation             │            0 │           0 │                          1 │                  59946 │  │
│ │ body_type               │         5296 │        8.83 │                          1 │                  61668 │  │
│ │ diet                    │        24395 │       40.69 │                        1.1 │                  63763 │  │
│ │ drinks                  │         2985 │        4.98 │                        1.1 │                  63966 │  │
│ │ drugs                   │        14080 │       23.49 │                       0.77 │                  45866 │  │
│ │ education               │         6628 │       11.06 │                          3 │                 181175 │  │
│ │ ethnicity               │         5680 │        9.48 │                        1.3 │                  77878 │  │
│ │ job                     │         8198 │       13.68 │                          3 │                 177460 │  │
│ │ last_online             │            0 │           0 │                          1 │                  59946 │  │
│ │ location                │            0 │           0 │                        2.7 │                 161626 │  │
│ │ offspring               │        35561 │       59.32 │                        1.8 │                 105720 │  │
│ │ pets                    │        19921 │       33.23 │                        2.6 │                 158146 │  │
│ │ religion                │        20226 │       33.74 │                          3 │                 182632 │  │
│ │ sign                    │        11056 │       18.44 │                        3.9 │                 235295 │  │
│ │ smokes                  │         5512 │        9.19 │                          1 │                  60434 │  │
│ │ speaks                  │           50 │        0.08 │                        3.1 │                 187527 │  │
│ └─────────────────────────┴──────────────┴─────────────┴────────────────────────────┴────────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯